name: ColoProbe

on:
  workflow_dispatch:
  push:
    paths:
      - 'py/scan_colo.py'

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install aiohttp
      - name: Run Colo probe
        run: python3 py/scan_colo.py 4 200
